# change the followings to match your Github username and repo name
# baseurl: "/Jeff9821.github.io" # the name of your github repo
baseurl: "" # the name of your github repo
url: "https://www.koelsch.dev" # the url of your github pages

# site information used in page title, meta data etc.
title: "Simon Kölsch Portfolio and Blog"
description: Portfolio website for Simon Kölsch

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Simon Kölsch
author-bio: System Engineer at DT  # change to false to hide
author-image: memoji.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: Home
    permalink: '#profile-container'
  - text: About
    permalink: '#about-me'
  - text: Projects
    permalink: '#projects'
  - text: Blog
    permalink: blog


# use false to turn off any social media links
github: https://github.com/Jeff9821
linkedin: https://www.linkedin.com/in/simon-k%C3%B6lsch-54207a224/
medium: false
google-scholar: false
email: false

# footer information
#footer-msg: "Powered by Tailpages"
#footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
